version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "8198:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
      - ./html:/usr/share/nginx/html:ro
    depends_on:
      - service1-1
      - service1-2
      - service1-3
    networks:
      - service-network

  service1-1:
    image: flask-service:latest
    build:
      dockerfile: Dockerfile
      context: ./service1
    expose:
      - "8199"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - service2
    networks:
      - service-network

  service1-2:
    image: flask-service:latest
    build:
      dockerfile: Dockerfile
      context: ./service1
    expose:
      - "8199"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - service2
    networks:
      - service-network

  service1-3:
    image: flask-service:latest
    build:
      dockerfile: Dockerfile
      context: ./service1
    expose:
      - "8199"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - service2
    networks:
      - service-network

  service2:
    image: node-service:latest
    build:
      dockerfile: Dockerfile
      context: ./service2
    expose:
      - "8080"
    networks:
      - service-network

networks:
  service-network:
    driver: bridge
